# Generated by Django 5.2.3 on 2025-07-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='plataforma',
        ),
        migrations.RenameField(
            model_name='reseña',
            old_name='contenido',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='reseña',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='puntaje',
        ),
        migrations.AddField(
            model_name='reseña',
            name='puntaje',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='consola',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='desarrollador',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='juegos.desarrollador'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Plataforma',
        ),
    ]
