# Generated by Django 5.2.4 on 2025-07-18 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_alter_reseña_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_videojuegos'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='desarrollador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.desarrollador'),
        ),
    ]
