# Generated by Django 5.2.4 on 2025-07-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_videojuego_logo_alter_videojuego_desarrollador'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='fecha_lanzamiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
